---
- name: Install Java
  apt:
    name: ['openjdk-11-jdk']
    state: latest    
  become: true
  

  #install PostgreSQL
- name: Add the PostgreSQL repository
  shell: sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'
  become: true

- name: Add the PostgreSQL signing key
  shell: wget -q https://www.postgresql.org/media/keys/ACCC4CF8.asc -O - | sudo apt-key add -
  become: true
  
- name: Install PostgreSQL
  apt: 
    name: ['postgresql', 'postgresql-contrib']
  become: true
  
- name: Copies correct PostgreSQL config file over
  copy:
    src: pg_hba.conf
    dest: /var/lib/postgresql/15/main/pg_hba.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  become: true   
  
  
- name: Enable and Start PostgreSQL
  service:
    name: postgresql
    state: started
    enabled: yes
  become: true
     
  #postgreSQL config
 
- name: Create Database for SonarQube
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true 
  become_method: sudo
  become_user: postgres  
  postgresql_db:
    name: 'sonar'
    encoding: UTF-8
  
  
- name: pd reset database user
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true
  become_method: sudo
  become_user: postgres
  postgresql_user: 
    db: sonar
    name: sonar
    password: "sonar" 
    priv: ALL



- name: Create SonarQube Directory
  file:
    path: '/etc/sonarqube'
    state: directory
    mode: 777
    
- name: Upgrading Software
  expect:
    command: unzip sonarqube-9.0.1.46107.zip
    responses:
      'First Question in the prompt' : 'y'
      'Second Question in the prompt' : 'y'
      
  #Download Sonarqube
- name: Download sonarqube v9.0.1 community version
  shell: wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.0.1.46107.zip
  
- name: unzip sonarqube
  shell: unzip sonarqube-9.0.1.46107.zip
  
- name: move file
  shell: cp -R ./sonarqube-9.0.1.46107 /etc/sonarqube


#Sonarqube config & start
- name: Template the correct properties file
  template:
    src: sonar.properties
    dest: /etc/sonarqube/sonarqube-9.0.1.46107/conf/sonar.properties
    owner: root
    group: wheel
    mode: 0644
  become: true

- name: copy service
  copy:
    src: sonar.service
    dest: /etc/systemd/system/sonar.service
  become: true

- name: Start and Enable Sonar Service
  service:
    name: sonar
    state: started
    enabled: yes
  become: true
