---
- name: Install Java
  apt:
    name: ['openjdk-11-jdk']
    state: latest    
  become: true
  

  #install PostgreSQL
- name: Add the PostgreSQL repository
  shell: sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'
  become: true

- name: Add the PostgreSQL signing key
  shell: wget -q https://www.postgresql.org/media/keys/ACCC4CF8.asc -O - | sudo apt-key add -
  become: true
  
- name: Install PostgreSQL
  apt: 
    name: ['postgresql', 'postgresql-contrib']
  become: true
  
- name: Copies correct PostgreSQL config file over
  copy:
    src: pg_hba.conf
    dest: /var/lib/postgresql/12/main/pg_hba.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  become: true   
  
  
- name: Enable and Start PostgreSQL
  service:
    name: postgresql
    state: started
    enabled: yes
  become: true
     
  #postgreSQL config
 
- name: Create Database for SonarQube
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: true 
  become_method: sudo
  become_user: postgres  
  postgresql_db:
    name: 'sonar'
    encoding: UTF-8

- name: Create db user
  postgresql_user:
        state: present
        name: "sonar"
        password: "sonar"
  become: yes
  become_user: postgres
  
- name: pd reset database user
  become: true
  become_method: sudo
  become_user: postgres
  postgresql_owner: 
    db: sonar
    new_owner: "sonar"
    password: "sonar" 
    priv: ALL

  #Download Sonarqube
- name: Download sonarqube v9.0.1 community version
  shell: wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.0.1.46107.zip
  
- name: unzip sonarqube
  shell: unzip sonarqube-9.0.1.46107.zip
     
- name: Edit the sysctl configuration file
  copy:
    src: sysctl.conf
    dest: /etc/sysctl.conf
    owner: root
    group: root
    mode: 0644
  become: true
  
- name: Edit /etc/security/limits.conf
  copy:
    src: limits.conf
    dest: /etc/security/limits.conf
    owner: root
    group: root
    mode: 0644
  become: true  
  
- name: move file
  shell: mv sonarqube-9.0.1.46107 /opt/sonarqube


#Sonarqube config & start
- name: Template the correct properties file
  template:
    src: sonar.properties
    dest: /opt/sonarqube/conf/sonar.properties
    owner: root
    group: root
    mode: 0644
  become: true

- name: copy service
  copy:
    src: sonar.service
    dest: /etc/systemd/system/sonar.service
  become: true

- name: Create a sonar group
  shell: groupadd sonar
  become: true
  
- name: Create a sonar user
  shell: useradd -d /opt/sonarqube -g sonar sonar
  become: true
  
- name: Grant the sonar user access
  shell: sudo chown sonar:sonar /opt/sonarqube -R
  become: true
  
#- name: move file sonar.sh  
 # copy:
  #  src: sonar.sh
   # dest: /opt/sonarqube/bin/linux-x86-64/sonar.sh
  #become: true
  
- name: Start and Enable Sonar Service
  service:
    name: sonar
    state: started
    enabled: yes
  become: true
