---
- hosts: localhost
  pre_tasks:
    - name: Update all the packages
      yum:
        name: '*'
        state: latest
      become: true
      when: ansible_os_family == 'RedHat'

    - name: Install Dependencies
      yum:
        name: ['unzip','curl','postgresql-libs','python-psycopg2','policycoreutils-python']
        state: latest
      become: true
      when: ansible_os_family == 'RedHat'

  roles:
    - {role: sonarqube }
