---
- hosts: localhost
  roles:
    -common
    - role: sonarqube
      become: yes
      vars:
        #try to convince not to look for python 2 stuff...
        #👇 (that's the python on my Ubuntu VM)
        ansible_python_interpreter: "/usr/bin/python3" 

  pre_tasks:
    - name: Update all the packages
      apt:
        name: '*'
        state: latest
      become: true
      

    - name: Install Dependencies
      apt:
        name: ['unzip','curl']
        state: latest
      become: true
      
    - name: install prerequisites    
      apt: 
        name: ['libpq-dev'] 
        state: latest
      become: true

    
    - name: Install requests python package
      pip:
        name: requests
      vars:
        ansible_python_interpreter: /usr/bin/python3
        
  roles:
    - {role: sonarqube }
