---
- hosts: localhost
  pre_tasks:
    - name: Update all the packages
      yum:
        name: '*'
        state: latest
      become: true
      when: ansible_os_family == 'RedHat'

    - name: Install Dependencies
      yum:
        name: '{{ item }}'
        state: latest
      with_items:
        - unzip #Used for Sonarqube installation
        - curl #Used to get the files       
        - postgresql-libs #used by psycopg2
        - python-psycopg2 #Used for PostgreSQL authentication
        - policycoreutils-python #Used to edit Selinux
      become: true
      when: ansible_os_family == 'RedHat'

  roles:
    - {role: sonarqube }
