---
- hosts: localhost
  pre_tasks:
    - name: Update all the packages
      apt:
        name: '*'
        state: latest
      become: true
      

    - name: Install Dependencies
      apt:
        name: ['unzip','curl', 'python-psycopg2','policycoreutils-python']
        state: latest
      become: true
      

  roles:
    - {role: sonarqube }
