---
- hosts: all
  roles:
   - role: sonarqube
     vars:
        ansible_python_interpreter: "/usr/bin/python3.8" 
     become: true  

  pre_tasks:
    - name: Update all the packages
      apt:
        name: '*'
        state: latest
      become: true
      

    - name: Install Dependencies
      apt:
        name: ['unzip','curl']
        state: latest
      become: true
      
   // - name: install prerequisites    
      //apt: 
       // name: ['python3-pip'] 
        //state: latest
      //become: true



